# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_06_texture
GAME_TITLE	:= DSP bench 06
GAME_SUBTITLE	:= Texture

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
