# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

SOURCEDIRS	:= arm9/source common
INCLUDEDIRS	:= common arm9/source
BINDIRS		:= arm9/data

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile.arm9
