# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_01_collision
GAME_TITLE	:= DSP bench 01
GAME_SUBTITLE	:= Collision

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
