#!/bin/bash
#
# SPDX-License-Identifier: CC0-1.0
#
# Runs every snippet of the probe in teaksim (the teakra emulator) and writes
# their results and cycle counts to common/probe_expected.h. Run it from the
# directory of the example after "make", and build again.

TEAKSIM=$(dirname "$0")/../../../../tools/teaksim/teaksim
N=$(grep -c '^    X([a-z0-9_]*)' common/probe.h)

{
    seq=1
    for ((j = 0; j < N; j++)); do
        seq=$(( seq % 15 + 1 ))
        printf 'cmd 2 %X 1\n' $(( 0x3000 | (seq << 8) | j ))
    done
    echo quit
} | "$TEAKSIM" build/teak.elf 2>/dev/null | grep '^rep' > /tmp/probe_expected.$$

{
    echo "// SPDX-License-Identifier: CC0-1.0"
    echo "//"
    echo "// Generated by host/gen_expected.sh: results and DSP cycles of the"
    echo "// snippets in the teakra emulator."
    echo
    echo "#ifndef PROBE_EXPECTED_H__"
    echo "#define PROBE_EXPECTED_H__"
    echo
    echo "#include <stdint.h>"
    echo
    echo "static const uint32_t probe_expected[] = {"
    awk '$2 !~ /^1/ { print "    0x" $3 "," }' /tmp/probe_expected.$$
    echo "};"
    echo
    echo "static const uint32_t probe_expected_cycles[] = {"
    awk '$2 ~ /^1/ { printf "    %d,\n", strtonum("0x" $3) }' /tmp/probe_expected.$$
    echo "};"
    echo
    echo "#endif // PROBE_EXPECTED_H__"
} > common/probe_expected.h

rm -f /tmp/probe_expected.$$
