# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= dsp_codegen_check
GAME_TITLE	:= DSP codegen
GAME_SUBTITLE	:= Check

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
