// SPDX-License-Identifier: CC0-1.0
//
// Small tests of the code generated by the Teak LLVM toolchain. The same source
// is built for the ARM9 and for the DSP, and the ARM9 compares the results.

#ifndef CGTESTS_H__
#define CGTESTS_H__

#include <stdint.h>

// Commands sent by the ARM9 in CMD0 (command | sequence number | index):
//
// - CG_CMD_INIT: Initializes the input data of the tests.
//   Reply: REP1 = number of tests, REP2 = 0.
// - CG_CMD_RUN | index: Runs a test.
//   Reply: REP1:REP2 = result.
// - CG_CMD_STATS: Reply: REP1:REP2 = number of repeated commands ignored.
//
// In all replies REP0 = sequence number | status.
//
// The sequence number (1 to 15) is copied to the reply. On hardware, the ARM9
// can see a reply that isn't new and the DSP can see the same command twice,
// so the DSP ignores a command with the same sequence number as the previous
// one, and the ARM9 ignores replies with the wrong sequence number.
#define CG_CMD_INIT         0x1000
#define CG_CMD_RUN          0x2000
#define CG_CMD_STATS        0x3000
#define CG_CMD_MASK         0xF000
#define CG_SEQ_SHIFT        8
#define CG_SEQ_MASK         (0xF << CG_SEQ_SHIFT)
#define CG_INDEX_MASK       0x00FF

#define CG_STATUS_OK        0
#define CG_STATUS_BAD_CMD   1
#define CG_STATUS_MASK      0x00FF

// Initializes the input data. Call it once before running the tests.
void cg_init(void);

// Number of tests
uint16_t cg_test_count(void);

// Runs a test and returns its result
uint32_t cg_run(uint16_t index);

#endif // CGTESTS_H__
