# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_07_perlin
GAME_TITLE	:= DSP bench 07
GAME_SUBTITLE	:= Perlin

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
