# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_02_skinning
GAME_TITLE	:= DSP bench 02
GAME_SUBTITLE	:= Skinning

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
