# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_08_math32
GAME_TITLE	:= DSP bench 08
GAME_SUBTITLE	:= 32-bit math

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
