# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_03_blur
GAME_TITLE	:= DSP bench 03
GAME_SUBTITLE	:= Blur

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
