# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_05_dct
GAME_TITLE	:= DSP bench 05
GAME_SUBTITLE	:= DCT

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
