# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_00_miu_probe
GAME_TITLE	:= DSP bench 00
GAME_SUBTITLE	:= MIU probe

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
