# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_04_fft
GAME_TITLE	:= DSP bench 04
GAME_SUBTITLE	:= FFT

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
