# SPDX-License-Identifier: CC0-1.0

BLOCKSDS	?= /opt/blocksds/core

NAME		:= dsp_bench_00_asm_probe
GAME_TITLE	:= DSP bench 00
GAME_SUBTITLE	:= Asm probe

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
